arch: resnet50
batch_size: 128
key_img_encoded: image
key_img_id: id
msgpack_train_dir: resources/images/mp16
msgpack_val_dir: resources/images/yfcc25600
num_workers_per_loader: 6
optim:
  params:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
partitionings:
  files:
  - resources/s2_cells/cells_50_5000.csv
  - resources/s2_cells/cells_50_2000.csv
  - resources/s2_cells/cells_50_1000.csv
  ptype: default
  shortnames:
  - coarse
  - middle
  - fine
scheduler:
  params:
    gamma: 0.5
    milestones:
    - 4
    - 8
    - 12
    - 13
    - 14
    - 15
train_label_mapping: resources/mp16_places365_mapping_h3.json
train_meta_path: resources/mp16_places365.csv
val_check_interval: 4000
val_label_mapping: resources/yfcc_25600_places365_mapping_h3.json
val_meta_path: resources/yfcc25600_places365.csv
weights: null
